/** Described a polling station. */
export interface PollingStation {
  label: string;
  labelCyr: string;
  embassy: string;
  embassyCyr: string;
  email: string;
}

export const POLLING_STATIONS: PollingStation[] = [
  {
    label: 'Afganistan (pokriva Ambasada Srbije u Indiji)',
    labelCyr: 'Авганистан (покрива Амбасада Србије у Индији)',
    embassy: 'Ambasada Srbije u Indiji',
    embassyCyr: 'Амбасада Србије у Индији',
    email: 'embassyofserbiadelhi@hotmail.com',
  }, {
    label: 'Albanija',
    labelCyr: 'Албанија',
    embassy: 'Ambasada Srbije u Albaniji',
    embassyCyr: 'Амбасада Србије у Албанији',
    email: 'ambatira@icc-al.org',
  }, {
    label: 'Alžir',
    labelCyr: 'Алжир',
    embassy: 'Ambasada Srbije u Alžiru',
    embassyCyr: 'Амбасада Србије у Алжиру',
    email: 'ambasada@ambserbie-alger.com',
  }, {
    label: 'Ambasada Srbije u Australiji, Kanbera',
    labelCyr: 'Амбасада Србије у Аустралији, Канбера',
    embassy: 'Ambasada Srbije u Australiji, Kanbera',
    embassyCyr: 'Амбасада Србије у Аустралији, Канбера',
    email: 'embassy.canberra@serbia.org.au',
  }, {
    label: 'Ambasada Srbije u Nemačkoj, Berlin',
    labelCyr: 'Амбасада Србије у Немачкој, Берлин',
    embassy: 'Ambasada Srbije u Nemačkoj, Berlin',
    embassyCyr: 'Амбасада Србије у Немачкој, Берлин',
    email: 'info@botschaft-serbien.de',
  }, {
    label: 'Ambasada Srbije u Švajcarskoj, Bern',
    labelCyr: 'Амбасада Србије у Швајцарској, Берн',
    embassy: 'Ambasada Srbije u Švajcarskoj, Bern',
    embassyCyr: 'Амбасада Србије у Швајцарској, Берн',
    email: 'info@ambasadasrbije.ch',
  }, {
    label: 'Andora (pokriva Ambasada Srbije u Španiji)',
    labelCyr: 'Андора (покрива Амбасада Србије у Шпанији)',
    embassy: 'Ambasada Srbije u Španiji',
    embassyCyr: 'Амбасада Србије у Шпанији',
    email: 'konz.madrid@mfa.rs',
  }, {
    label: 'Angola',
    labelCyr: 'Ангола',
    embassy: 'Ambasada Srbije u Angoli',
    embassyCyr: 'Амбасада Србије у Анголи',
    email: 'serbiaemb@netcabo.co.ao',
  }, {
    label: 'Antigva i Barbuda (pokriva Ambasada Srbije u SAD, Vašington)',
    labelCyr: 'Антигва и Барбуда (покрива Амбасада Србије у САД, Вашингтон)',
    embassy: 'Ambasada Srbije u Sjedinjenim Američkim Državama, Vašington',
    embassyCyr: 'Амбасада Србије у Сједињеним Америчким Државама, Васхингтон',
    email: 'consular@serbiaembusa.org',
  }, {
    label: 'Argentina',
    labelCyr: 'Аргентина',
    embassy: 'Ambasada Srbije u Argentini',
    embassyCyr: 'Амбасада Србије у Аргентини',
    email: 'consulado@serbembaires.com.ar',
  }, {
    label: 'Australija, Sidnej (konzulat)',
    labelCyr: 'Аустралија, Сиднеј (конзулат)',
    embassy: 'Konzulat Srbije u Australiji, Sidnej',
    embassyCyr: 'Конзулат Србије у Аустралији, Сиднеј',
    email: 'gkrssid@optusnet.com.au',
  }, {
    label: 'Austrija, Beč',
    labelCyr: 'Аустрија, Беч',
    embassy: 'Ambasada Srbije u Austriji, Beč',
    embassyCyr: 'Амбасада Србије у Аустрији, Беч',
    email: 'consulate.vienna@mfa.rs',
  }, {
    label: 'Austrija, Salcburg (konzulat)',
    labelCyr: 'Аустрија, Салцбург (конзулат)',
    embassy: 'Konzulat Srbije u Austriji, Salcburg',
    embassyCyr: 'Конзулат Србије у Аустрији, Салцбург',
    email: 'genconsulate.salzburg@mfa.rs',
  }, {
    label: 'Azerbejdžan',
    labelCyr: 'Азербејџан',
    embassy: 'Ambasada Srbije u Azerbejdžanu',
    embassyCyr: 'Амбасада Србије у Азербејџану',
    email: 'serbianembassy.baku@azeurotel.com',
  }, {
    label: 'Bahami (pokriva Ambasada Srbije u SAD, Vašington)',
    labelCyr: 'Бахами (поклопци Амбасада Србије у Сједињеним Америчким Државама, Вашингтон)',
    embassy: 'Ambasada Srbije u Sjedinjenim Američkim Državama, Vašington',
    embassyCyr: 'Амбасада Србије у Сједињеним Америчким Државама, Васхингтон',
    email: 'consular@serbiaembusa.org',
  }, {
    label: 'Bahrein (pokriva Ambasada Srbije u Kuvajtu)',
    labelCyr: 'Бахреин (покрива Амбасада Србије у Кувајту)',
    embassy: 'Ambasada Srbije u Kuvajtu',
    embassyCyr: 'Амбасада Србије у Кувајту',
    email: 'serbkonzkw@gmail.com',
  }, {
    label: 'Bangladeš (pokriva Ambasada Srbije u Indiji)',
    labelCyr: 'Бангладеш (покрива Амбасада Србије у Индији)',
    embassy: 'Ambasada Srbije u Indiji',
    embassyCyr: 'Амбасада Србије у Индији',
    email: 'embassyofserbiadelhi@hotmail.com',
  }, {
    label: 'Barbados (pokriva Ambasada Srbije u SAD, Vašington)',
    labelCyr: 'Барбадос (поклопци Амбасада Србије у Сједињеним Америчким Државама, Вашингтон)',
    embassy: 'Ambasada Srbije u Sjedinjenim Američkim Državama, Vašington',
    embassyCyr: 'Амбасада Србије у Сједињеним Америчким Државама, Васхингтон',
    email: 'consular@serbiaembusa.org',
  }, {
    label: 'Belgija',
    labelCyr: 'Белгија',
    embassy: 'Ambasada Srbije u Belgiji',
    embassyCyr: 'Амбасада Србије у Белгији',
    email: 'embassy.brussels@mfa.rs',
  }, {
    label: 'Belize (pokriva Ambasada Srbije u SAD, Vašington)',
    labelCyr: 'Белизе (поклопци Амбасада Србије у Сједињеним Америчким Државама, Вашингтон)',
    embassy: 'Ambasada Srbije u Sjedinjenim Američkim Državama, Vašington',
    embassyCyr: 'Амбасада Србије у Сједињеним Америчким Државама, Васхингтон',
    email: 'consular@serbiaembusa.org',
  }, {
    label: 'Belorusija',
    labelCyr: 'беларус',
    embassy: 'Ambasada Srbije u Belorusiji',
    embassyCyr: 'Амбасада Србије у Белорусији',
    email: 'embassy.minsk@mfa.rs',
  }, {
    label: 'Benin (pokriva UN - Njujork)',
    labelCyr: 'Бенина (покрива Уједињених нација - Нев Иорк)',
    embassy: 'UN - Njujork',
    embassyCyr: 'УН-а - Њујорк',
    email: 'info@serbiamissionun.org',
  }, {
    label: 'Bocvana (pokriva Ambasada Srbije u Južnoafričkoj Republici)',
    labelCyr: 'Боцвана (покрива Амбасада Србије у Републици Јужној Африци)',
    embassy: 'Ambasada Srbije u Južnoafričkoj Republici',
    embassyCyr: 'Амбасада Србије у Јужној Африци',
    email: 'info@srbembassy.org.za',
  }, {
    label: 'Bolivija (pokriva Ambasada Srbije u Brazilu)',
    labelCyr: 'Боливија (покрива Амбасада Србије у Бразилу)',
    embassy: 'Ambasada Srbije u Brazilu',
    embassyCyr: 'Амбасада Србије у Бразилу',
    email: 'embaixadaservia@terra.com.br',
  }, {
    label: 'Bosna i Hercegovina, Banja Luka (konzulat)',
    labelCyr: 'Босна и Херцеговина, Бања Лука (конзулат)',
    embassy: 'Konzulat Srbije u Bosni i Hercegovini, Banja Luka',
    embassyCyr: 'Конзулат Србије у Босни и Херцеговини, Бања Лука',
    email: 'konzulat.bl@mfa.rs',
  }, {
    label: 'Bosna i Hercegovina, Drvar (konzulat)',
    labelCyr: 'Босна и Херцеговина, Дрвар (конзулат)',
    embassy: 'Konzulat Srbije u Bosni i Hercegovini, Drvar',
    embassyCyr: 'Конзулат Србије у Босни и Херцеговини, Дрвар',
    email: 'kk.rs-drvar@ktsara.net',
  }, {
    label: 'Bosna i Hercegovina, Mostar (konzulat)',
    labelCyr: 'Босна и Херцеговина, Мостар (конзулат)',
    embassy: 'Konzulat Srbije u Bosni i Hercegovini, Mostar',
    embassyCyr: 'Конзулат Србије у Босни и Херцеговини, Мостар',
    email: 'gk.mostar@mfa.rs',
  }, {
    label: 'Bosna i Hercegovina, Trebinje (konzulat)',
    labelCyr: 'Босна и Херцеговина, Требиње (конзулат)',
    embassy: 'Konzulat Srbije u Bosni i Hercegovini, Trebinje',
    embassyCyr: 'Конзулат Србије у Босни и Херцеговини, Требиње',
    email: 'kk.trebinje@mfa.rs',
  }, {
    label: 'Bosni i Hercegovina, Sarajevo',
    labelCyr: 'Босни и Херцеговина, Сарајево',
    embassy: 'Ambasada Srbije u Bosni i Hercegovini, Sarajevo',
    embassyCyr: 'Амбасада Србије у Босни и Херцеговини, Сарајево',
    email: 'srbamba@bih.net.ba',
  }, {
    label: 'Brazil',
    labelCyr: 'Бразил',
    embassy: 'Ambasada Srbije u Brazilu',
    embassyCyr: 'Амбасада Србије у Бразилу',
    email: 'embaixadaservia@terra.com.br',
  }, {
    label: 'Brunej Darusalam (pokriva Ambasada Srbije u Indoneziji)',
    labelCyr: 'Брунеј Дарусалам (покрива Амбасада Србије у Индонезији)',
    embassy: 'Ambasada Srbije u Indoneziji',
    embassyCyr: 'Амбасада Србије у Индонезији',
    email: 'embjakarta@serbian-embassy.org',
  }, {
    label: 'Bugarska',
    labelCyr: 'Бугарска',
    embassy: 'Ambasada Srbije u Bugarskoj',
    embassyCyr: 'Амбасада Србије у Бугарској',
    email: 'sofia@emb-serbia.com',
  }, {
    label: 'Burkina Faso (pokriva UN - Njujork)',
    labelCyr: 'Буркине Фасо (покрива Уједињене нације - Њујорк)',
    embassy: 'UN - Njujork',
    embassyCyr: 'УН-а - Њујорк',
    email: 'info@serbiamissionun.org',
  }, {
    label: 'Burundi (pokriva Ambasada Srbije u Keniji)',
    labelCyr: 'Бурунди, (покрива амбасада Србије у Кенији)',
    embassy: 'Ambasada Srbije u Keniji',
    embassyCyr: 'Амбасада Србије у Кенији',
    email: 'nairobi@embassyofserbia.or.ke',
  }, {
    label: 'Butan (pokriva Ambasada Srbije u Indiji)',
    labelCyr: 'Бутан (покрива Амбасада Србије у Индији)',
    embassy: 'Ambasada Srbije u Indiji',
    embassyCyr: 'Амбасада Србије у Индији',
    email: 'embassyofserbiadelhi@hotmail.com',
  }, {
    label: 'Čad (pokriva Ambasada Srbije u Libiji)',
    labelCyr: 'Чад (покривен либијске амбасаде Србије)',
    embassy: 'Ambasada Srbije u Libiji',
    embassyCyr: 'Амбасада Србије у Либији',
    email: 'serbianembassy_tripoli@yahoo.com',
  }, {
    label: 'Centralnoafrička Republika (pokriva UN - Njujork)',
    labelCyr: 'Централна Афричка Република (покривен од стране УН - Нев Иорк)',
    embassy: 'UN - Njujork',
    embassyCyr: 'УН-а - Њујорк',
    email: 'info@serbiamissionun.org',
  }, {
    label: 'Češka Republika',
    labelCyr: 'Чешка',
    embassy: 'Ambasada Srbije u Češkoj Republici',
    embassyCyr: 'Амбасада Србије у Чешкој Републици',
    email: 'konzularno.prag@mfa.rs',
  }, {
    label: 'Čile (pokriva Ambasada Srbije u Argentini)',
    labelCyr: 'Чиле (покрива Амбасада Србије у Аргентини)',
    embassy: 'Ambasada Srbije u Argentini',
    embassyCyr: 'Амбасада Србије у Аргентини',
    email: 'consulado@serbembaires.com.ar',
  }, {
    label: 'Crna Gora, Herceg Novi (konzulat)',
    labelCyr: 'Црна Гора, Херцег Нови (конзулат)',
    embassy: 'Konzulat Srbije u Crnoj Gori, Herceg Novi',
    embassyCyr: 'Конзулат Србије у Црној Гори, Херцег Нови',
    email: 'gkh.novi@mfa.rs',
  }, {
    label: 'Crna Gora, Podgorica',
    labelCyr: 'Црна Гора, Подгорица',
    embassy: 'Ambasada Srbije u Crnoj Gori, Podgorica',
    embassyCyr: 'Амбасада Србије у Црној Гори, Подгорица',
    email: 'embassy.podgorica@mfa.rs',
  }, {
    label: 'Danska',
    labelCyr: 'Данска',
    embassy: 'Ambasada Srbije u Danskoj',
    embassyCyr: 'Амбасада Србије у Данској',
    email: 'serbianemb@city.dk',
  }, {
    label: 'Dominikana (pokriva Ambasada Srbije u SAD, Vašington)',
    labelCyr: 'Доминикана (покрива Амбасада Србије у САД, Вашингтон)',
    embassy: 'Ambasada Srbije u Sjedinjenim Američkim Državama, Vašington',
    embassyCyr: 'Амбасада Србије у Сједињеним Америчким Државама, Васхингтон',
    email: 'consular@serbiaembusa.org',
  }, {
    label: 'Dominikanska Republika (pokriva Ambasada Srbije na Kubi)',
    labelCyr: 'Доминиканска Република (покрива Амбасада Србије на Куби)',
    embassy: 'Ambasada Srbije na Kubi',
    embassyCyr: 'Амбасада Србије на Куби',
    email: 'konzsrbhav@gmail.com',
  }, {
    label: 'Džibuti (pokriva Ambasada Srbije u Etiopiji)',
    labelCyr: 'Џибути (покрива Амбасада Србије у Етиопији)',
    embassy: 'Ambasada Srbije u Etiopiji',
    embassyCyr: 'Амбасада Србије у Етиопији',
    email: 'serbambadis@yahoo.com',
  }, {
    label: 'Egipat',
    labelCyr: 'Египат',
    embassy: 'Ambasada Srbije u Egipatu',
    embassyCyr: 'Амбасада Србије у Египату',
    email: 'konzul@serbiaeg.com',
  }, {
    label: 'Ekvador (pokriva Ambasada Srbije u Brazilu)',
    labelCyr: 'Еквадор (покрива Амбасада Србије у Бразилу)',
    embassy: 'Ambasada Srbije u Brazilu',
    embassyCyr: 'Амбасада Србије у Бразилу',
    email: 'embaixadaservia@terra.com.br',
  }, {
    label: 'Ekvatorijalna Gvineja (pokriva Ambasada Srbije u Angoli)',
    labelCyr: 'Гвинеја (покрива Амбасада Србије у Анголи)',
    embassy: 'Ambasada Srbije u Angoli',
    embassyCyr: 'Амбасада Србије у Анголи',
    email: 'serbiaemb@netcabo.co.ao',
  }, {
    label: 'Eritreja (pokriva Ambasada Srbije u Keniji)',
    labelCyr: 'Еритреја (поклопци Амбасада Србије у Кенији)',
    embassy: 'Ambasada Srbije u Keniji',
    embassyCyr: 'Амбасада Србије у Кенији',
    email: 'nairobi@embassyofserbia.or.ke',
  }, {
    label: 'Estonija (pokriva Ambasada Srbije u Finskoj)',
    labelCyr: 'Естонија (покрива Амбасада Србије у Финској)',
    embassy: 'Ambasada Srbije u Finskoj',
    embassyCyr: 'Амбасада Србије у Финској',
    email: 'serbia@kolumbus.fi',
  }, {
    label: 'Etiopija',
    labelCyr: 'Етиопија',
    embassy: 'Ambasada Srbije u Etiopiji',
    embassyCyr: 'Амбасада Србије у Етиопији',
    email: 'serbambadis@yahoo.com',
  }, {
    label: 'Fidži (pokriva Ambasada Srbije u Australiji, Kanbera)',
    labelCyr: 'Фиџи (покрива Амбасада Србије у Аустралији, Канбера)',
    embassy: 'Ambasada Srbije u Australiji, Kanbera',
    embassyCyr: 'Амбасада Србије у Аустралији, Канбера',
    email: 'embassy.canberra@serbia.org.au',
  }, {
    label: 'Filipini (pokriva Ambasada Srbije u Indoneziji)',
    labelCyr: 'Филипини (покрива Амбасада Србије у Индонезији)',
    embassy: 'Ambasada Srbije u Indoneziji',
    embassyCyr: 'Амбасада Србије у Индонезији',
    email: 'embjakarta@serbian-embassy.org',
  }, {
    label: 'Finska',
    labelCyr: 'Финска',
    embassy: 'Ambasada Srbije u Finskoj',
    embassyCyr: 'Амбасада Србије у Финској',
    email: 'serbia@kolumbus.fi',
  }, {
    label: 'Francuska, Pariz',
    labelCyr: 'Француска, Париз',
    embassy: 'Ambasada Srbije u Francuskoj, Pariz',
    embassyCyr: 'Амбасада Србије у Француској, Париз',
    email: 'konzularno.pariz@mfa.rs',
  }, {
    label: 'Francuska, Strazbur (konzulat)',
    labelCyr: 'Француска, Стразбур (конзулат)',
    embassy: 'Konzulat Srbije u Francuskoj, Strazbur',
    embassyCyr: 'Конзулат Србије у Француској, Стразбур',
    email: 'consulate.strasbourg@mfa.rs',
  }, {
    label: 'Gabon (pokriva Ambasada Srbije u Angoli)',
    labelCyr: 'Габон (покрива Амбасада Србије у Анголи)',
    embassy: 'Ambasada Srbije u Angoli',
    embassyCyr: 'Амбасада Србије у Анголи',
    email: 'serbiaemb@netcabo.co.ao',
  }, {
    label: 'Gambija (pokriva UN - Njujork)',
    labelCyr: 'Гамбија (покривен од стране УН - Нев Иорк)',
    embassy: 'UN - Njujork',
    embassyCyr: 'УН-а - Њујорк',
    email: 'info@serbiamissionun.org',
  }, {
    label: 'Gana (pokriva Ambasada Srbije u Nigeriji)',
    labelCyr: 'Гана (покрива Амбасада Србије у Нигерији)',
    embassy: 'Ambasada Srbije u Nigeriji',
    embassyCyr: 'Амбасада Србије у Нигерији',
    email: 'serbconsabuja@gmail.com',
  }, {
    label: 'Grčka, Atina',
    labelCyr: 'Грчка, Атина',
    embassy: 'Ambasada Srbije u Grčkoj, Atina',
    embassyCyr: 'Амбасада Србије у Грчкој, Атина',
    email: 'embassy.athens.consular@mfa.rs',
  }, {
    label: 'Grčka, Solun (konzulat)',
    labelCyr: 'Грчка, Солун (конзулат)',
    embassy: 'Konzulat Srbije u Grčkoj, Solun',
    embassyCyr: 'Конзулат Србије у Грчкој, Солун',
    email: 'srbcons@otenet.gr',
  }, {
    label: 'Grenada (pokriva Ambasada Srbije u SAD, Vašington)',
    labelCyr: 'Гренада (покрива Амбасада Србије у САД, Вашингтон)',
    embassy: 'Ambasada Srbije u Sjedinjenim Američkim Državama, Vašington',
    embassyCyr: 'Амбасада Србије у Сједињеним Америчким Државама, Васхингтон',
    email: 'consular@serbiaembusa.org',
  }, {
    label: 'Gruzija (pokriva Ambasada Srbije u Ukrajini)',
    labelCyr: 'Грузија (покрива Амбасада Србије у Украјини)',
    embassy: 'Ambasada Srbije u Ukrajini',
    embassyCyr: 'Амбасада Србије у Украјини',
    email: 'konzrs@ukr.net',
  }, {
    label: 'Gvajana (pokriva Ambasada Srbije u SAD, Vašington)',
    labelCyr: 'Гвајана (поклопци Амбасада Србије у Сједињеним Америчким Државама, Вашингтон)',
    embassy: 'Ambasada Srbije u Sjedinjenim Američkim Državama, Vašington',
    embassyCyr: 'Амбасада Србије у Сједињеним Америчким Државама, Васхингтон',
    email: 'consular@serbiaembusa.org',
  }, {
    label: 'Gvatemala (pokriva Ambasada Srbije u Meksiku)',
    labelCyr: 'Гватемала (покрива Амбасада Србије у Мексику)',
    embassy: 'Ambasada Srbije u Meksiku',
    embassyCyr: 'Амбасада Србије у Мексику',
    email: 'embajadaserbia@alestra.net.mx',
  }, {
    label: 'Gvineja (pokriva Ambasada Srbije u Alžiru)',
    labelCyr: 'Гвинеја (покрива Амбасада Србије у Алжиру)',
    embassy: 'Ambasada Srbije u Alžiru',
    embassyCyr: 'Амбасада Србије у Алжиру',
    email: 'ambasada@ambserbie-alger.com',
  }, {
    label: 'Gvineja Bisao (pokriva Ambasada Srbije u Alžiru)',
    labelCyr: 'Гвинеја Бисао (покрива Амбасада Србије у Алжиру)',
    embassy: 'Ambasada Srbije u Alžiru',
    embassyCyr: 'Амбасада Србије у Алжиру',
    email: 'ambasada@ambserbie-alger.com',
  }, {
    label: 'Haiti (pokriva Ambasada Srbije na Kubi)',
    labelCyr: 'Хаити (покрива Амбасада Србије на Куби)',
    embassy: 'Ambasada Srbije na Kubi',
    embassyCyr: 'Амбасада Србије на Куби',
    email: 'konzsrbhav@gmail.com',
  }, {
    label: 'Holandija',
    labelCyr: 'Низоземска',
    embassy: 'Ambasada Srbije u Holandiji',
    embassyCyr: 'Амбасада Србије у Холандији',
    email: 'embassy.hague@mfa.rs',
  }, {
    label: 'Honduras (pokriva Ambasada Srbije u Meksiku)',
    labelCyr: 'Хондурас (покрива Амбасада Србије у Мексику)',
    embassy: 'Ambasada Srbije u Meksiku',
    embassyCyr: 'Амбасада Србије у Мексику',
    email: 'embajadaserbia@alestra.net.mx',
  }, {
    label: 'Hrvatska, Rijeka (konzulat)',
    labelCyr: 'Хрватска, Ријека (конзулат)',
    embassy: 'Konzulat Srbije u Hrvatskoj, Rijeka',
    embassyCyr: 'Конзулат Србије у Хрватској, Ријека',
    email: 'konzulat-rijeka@ri.t-com.hr',
  }, {
    label: 'Hrvatska, Vukovar (konzulat)',
    labelCyr: 'Хрватска, Вуковар (конзулат)',
    embassy: 'Konzulat Srbije u Hrvatskoj, Vukovar',
    embassyCyr: 'Конзулат Србије у Хрватској, Вуковар',
    email: 'generalni.konzulat@gk-srbije-vukovar.hr',
  }, {
    label: 'Hrvatska, Zagreb',
    labelCyr: 'Хрватска, Загреб',
    embassy: 'Ambasada Srbije u Hrvatskoj, Zagreb',
    embassyCyr: 'Амбасада Србије у Хрватској, Загреб',
    email: 'embassy.zagreb@mfa.rs',
  }, {
    label: 'Indija',
    labelCyr: 'Индија',
    embassy: 'Ambasada Srbije u Indiji',
    embassyCyr: 'Амбасада Србије у Индији',
    email: 'embassyofserbiadelhi@hotmail.com',
  }, {
    label: 'Indonezija',
    labelCyr: 'Индонезија',
    embassy: 'Ambasada Srbije u Indoneziji',
    embassyCyr: 'Амбасада Србије у Индонезији',
    email: 'embjakarta@serbian-embassy.org',
  }, {
    label: 'Irak',
    labelCyr: 'Ирак',
    embassy: 'Ambasada Srbije u Iraku',
    embassyCyr: 'Амбасада Србије у Ираку',
    email: 'embsrbag@yahoo.com',
  }, {
    label: 'Iran',
    labelCyr: 'Иран',
    embassy: 'Ambasada Srbije u Iranu',
    embassyCyr: 'Амбасада Србије у Ирану',
    email: 'serbembteh@neda.net',
  }, {
    label: 'Irska (pokriva Ambasada Srbije u Velikoj Britaniji)',
    labelCyr: 'Ирска (покрива Амбасада Србије у Великој Британији)',
    embassy: 'Ambasada Srbije u Velikoj Britaniji',
    embassyCyr: 'Амбасада Србије у Великој Британији',
    email: 'izbori2020@serbianembassy.org.uk',
  }, {
    label: 'Island (preko Ambasada Srbije u Norveškoj)',
    labelCyr: 'Исланд (преко Амбасада Србије у Норвешкој)',
    embassy: 'Ambasada Srbije u Norveškoj',
    embassyCyr: 'Амбасада Србије у Норвешкој',
    email: 'ambasada@serbianembassy.no',
  }, {
    label: 'Istočni Timor (pokriva Ambasada Srbije u Indoneziji)',
    labelCyr: 'Источни Тимор (покрива Амбасада Србије у Индонезији)',
    embassy: 'Ambasada Srbije u Indoneziji',
    embassyCyr: 'Амбасада Србије у Индонезији',
    email: 'embjakarta@serbian-embassy.org',
  }, {
    label: 'Italija, Milano (konzulat)',
    labelCyr: 'Италија, Милано (конзулат)',
    embassy: 'Konzulat Srbije u Italiji, Milano',
    embassyCyr: 'Конзулат Србије у Италији, Милано',
    email: 'info@gkrsmi.it',
  }, {
    label: 'Italija, Rim',
    labelCyr: 'Италија, Рим',
    embassy: 'Ambasada Srbije u Italiji, Rim',
    embassyCyr: 'Амбасада Србије у Италији, Рим',
    email: 'ljubomir.merdovic@mfa.rs',
  }, {
    label: 'Italija, Trst (konzulat)',
    labelCyr: 'Италија, Трст (конзулат)',
    embassy: 'Konzulat Srbije u Italiji, Trst',
    embassyCyr: 'Конзулат Србије у Италији, Трст',
    email: 'gkrstrst@spin.it',
  }, {
    label: 'Izrael',
    labelCyr: 'Израел',
    embassy: 'Ambasada Srbije u Izraelu',
    embassyCyr: 'Амбасада Србије у Израелу',
    email: 'srbambil@netvision.net.il',
  }, {
    label: 'Jamajka (pokriva Ambasada Srbije na Kubi)',
    labelCyr: 'Јамајка (покрива Амбасада Србије на Куби)',
    embassy: 'Ambasada Srbije na Kubi',
    embassyCyr: 'Амбасада Србије на Куби',
    email: 'konzsrbhav@gmail.com',
  }, {
    label: 'Japan',
    labelCyr: 'Јапан',
    embassy: 'Ambasada Srbije u Japanu',
    embassyCyr: 'Амбасада Србије у Јапану',
    email: 'embassy.tokyo@mfa.rs',
  }, {
    label: 'Jemen (pokriva Ambasada Srbije u Kuvajtu)',
    labelCyr: 'Јемен (покрива Амбасада Србије у Кувајту)',
    embassy: 'Ambasada Srbije u Kuvajtu',
    embassyCyr: 'Амбасада Србије у Кувајту',
    email: 'serbkonzkw@gmail.com',
  }, {
    label: 'Jermenija (pokriva Ambasada Srbije u Grčkoj, Atina)',
    labelCyr: 'Јерменија (покрива Амбасада Србије у Грчкој, Атина)',
    embassy: 'Ambasada Srbije u Grčkoj, Atina',
    embassyCyr: 'Амбасада Србије у Грчкој, Атина',
    email: 'embassy.athens.consular@mfa.rs',
  }, {
    label: 'Jordan (pokriva Ambasada Srbije u Libanu)',
    labelCyr: 'Јордан (покрива Амбасада Србије у Либану)',
    embassy: 'Ambasada Srbije u Libanu',
    embassyCyr: 'Амбасада Србије у Либану',
    email: 'embassy@serbia-beirut.rs',
  }, {
    label: 'Južna Koreja, Republika',
    labelCyr: 'Јужна Кореја, Република',
    embassy: 'Ambasada Srbije u Koreji, Republika',
    embassyCyr: 'Амбасада Србије у Кореји, Република',
    email: 'embserbseul@yahoo.com',
  }, {
    label: 'Južnoafrička Republika',
    labelCyr: 'Република, Јужна',
    embassy: 'Ambasada Srbije u Južnoafričkoj Republici',
    embassyCyr: 'Амбасада Србије у Јужној Африци',
    email: 'info@srbembassy.org.za',
  }, {
    label: 'Kambodža (pokriva Ambasada Srbije u Indoneziji)',
    labelCyr: 'Камбоџа (покрива Амбасада Србије у Индонезији)',
    embassy: 'Ambasada Srbije u Indoneziji',
    embassyCyr: 'Амбасада Србије у Индонезији',
    email: 'embjakarta@serbian-embassy.org',
  }, {
    label: 'Kamerun (pokriva UN - Njujork)',
    labelCyr: 'Камерун (покрива Уједињене нације - Њујорк)',
    embassy: 'UN - Njujork',
    embassyCyr: 'УН-а - Њујорк',
    email: 'info@serbiamissionun.org',
  }, {
    label: 'Kanada, Otava',
    labelCyr: 'Канада, Велика кола',
    embassy: 'Ambasada Srbije u Kanadi, Otava',
    embassyCyr: 'Амбасада Србије у Канади, Отава',
    email: 'diplomat@serbianembassy.ca',
  }, {
    label: 'Kanada, Toronto (konzulat)',
    labelCyr: 'Канада, Торонто (конзулат)',
    embassy: 'Konzulat Srbije u Kanadi, Toronto',
    embassyCyr: 'Конзулат Србије у Канади, Торонто',
    email: 'gkrstoronto@rogers.com',
  }, {
    label: 'Katar',
    labelCyr: 'катар',
    embassy: 'Ambasada Srbije u Kataru',
    embassyCyr: 'Амбасада Србије у Катару',
    email: 'embsrbqat@gmail.com',
  }, {
    label: 'Kazahstan',
    labelCyr: 'Казахстан',
    embassy: 'Ambasada Srbije u Kazahstanu',
    embassyCyr: 'Амбасада Србије у Казахстану',
    email: 'amb.astana@mail.ru',
  }, {
    label: 'Kenija',
    labelCyr: 'Кенија',
    embassy: 'Ambasada Srbije u Keniji',
    embassyCyr: 'Амбасада Србије у Кенији',
    email: 'nairobi@embassyofserbia.or.ke',
  }, {
    label: 'Kina, Narodna Republika, Peking',
    labelCyr: 'Кина, Народна Република, Пекинг',
    embassy: 'Ambasada Srbije u Kini, Narodna Republika, Peking',
    embassyCyr: 'Амбасада Србије у Кини, Народна Република, Пекинг',
    email: 'embserbia@embserbia.cn',
  }, {
    label: 'Kina, Narodna Republika, Šangaj (konzulat)',
    labelCyr: 'Кина, Народна Република, Шангај (конзулат)',
    embassy: 'Konzulat Srbije u Kini, Narodna Republika, Šangaj',
    embassyCyr: 'Конзулат Србије у Кини, Народна Република, Шангај',
    email: 'consulate@srbshanghai.org',
  }, {
    label: 'Kipar',
    labelCyr: 'вајар',
    embassy: 'Ambasada Srbije na Kipru',
    embassyCyr: 'Амбасада Србије на Кипру',
    email: 'nicosia@serbia.org.cy',
  }, {
    label: 'Kirgistan (pokriva Ambasada Srbije u Rusiji)',
    labelCyr: 'Киргистан (покрива Амбасада Србије у Русији)',
    embassy: 'Ambasada Srbije u Rusiji',
    embassyCyr: 'Амбасада Србије у Русији',
    email: 'konzularno.moskva@mfa.rs',
  }, {
    label: 'Kolumbija (pokriva Ambasada Srbije u SAD, Vašington)',
    labelCyr: 'Колумбија (покрива Амбасада Србије у САД, Вашингтон)',
    embassy: 'Ambasada Srbije u Sjedinjenim Američkim Državama, Vašington',
    embassyCyr: 'Амбасада Србије у Сједињеним Америчким Државама, Васхингтон',
    email: 'consular@serbiaembusa.org',
  }, {
    label: 'Komori (pokriva Ambasada Srbije u Keniji)',
    labelCyr: 'Комори (покрива Амбасада Србије у Кенији)',
    embassy: 'Ambasada Srbije u Keniji',
    embassyCyr: 'Амбасада Србије у Кенији',
    email: 'nairobi@embassyofserbia.or.ke',
  }, {
    label: 'Kondo, DR',
    labelCyr: 'Кондо ДР',
    embassy: 'Ambasada Srbije u Kongu, DR',
    embassyCyr: 'Амбасада Србије у Конгу, ДР',
    email: 'serbambakin@gmail.com',
  }, {
    label: 'Kongo (pokriva Ambasada Srbije u Angoli)',
    labelCyr: 'Конго (покрива Амбасада Србије у Анголи)',
    embassy: 'Ambasada Srbije u Angoli',
    embassyCyr: 'Амбасада Србије у Анголи',
    email: 'serbiaemb@netcabo.co.ao',
  }, {
    label: 'Koreja, DNR (pokriva Ambasada Srbije u Kini, Narodna Republika, Peking)',
    labelCyr: 'Кореја, ДНР (покрива Амбасада Србије у Кини, Народна Република, Пекинг)',
    embassy: 'Ambasada Srbije u Kini, Narodna Republika, Peking',
    embassyCyr: 'Амбасада Србије у Кини, Народна Република, Пекинг',
    email: 'embserbia@embserbia.cn',
  }, {
    label: 'Kostarika (pokriva Ambasada Srbije u Meksiku)',
    labelCyr: 'Костарика (покрива амбасада Србије у Мексику)',
    embassy: 'Ambasada Srbije u Meksiku',
    embassyCyr: 'Амбасада Србије у Мексику',
    email: 'embajadaserbia@alestra.net.mx',
  }, {
    label: 'Kuba',
    labelCyr: 'куба',
    embassy: 'Ambasada Srbije na Kubi',
    embassyCyr: 'Амбасада Србије на Куби',
    email: 'konzsrbhav@gmail.com',
  }, {
    label: 'Kuvajt',
    labelCyr: 'Кувајт',
    embassy: 'Ambasada Srbije u Kuvajtu',
    embassyCyr: 'Амбасада Србије у Кувајту',
    email: 'serbkonzkw@gmail.com',
  }, {
    label: 'Laos (pokriva Ambasada Srbije u Mjanmaru)',
    labelCyr: 'Лаос (покрива Амбасада Србије у Мјанмару)',
    embassy: 'Ambasada Srbije u Mjanmaru',
    embassyCyr: 'Амбасада Србије у Мјанмару',
    email: 'serbemb@yangon.net.mm',
  }, {
    label: 'Lesoto (pokriva Ambasada Srbije u Južnoafričkoj Republici)',
    labelCyr: 'Лесото (покрива Амбасада Србије у Републици Јужној Африци)',
    embassy: 'Ambasada Srbije u Južnoafričkoj Republici',
    embassyCyr: 'Амбасада Србије у Јужној Африци',
    email: 'info@srbembassy.org.za',
  }, {
    label: 'Letonija (pokriva Ambasada Srbije u Švedskoj)',
    labelCyr: 'Летонија (покрива Амбасада Србије у Шведској)',
    embassy: 'Ambasada Srbije u Švedskoj',
    embassyCyr: 'Амбасада Србије у Шведској',
    email: 'serbiaemb@telia.com',
  }, {
    label: 'Liban',
    labelCyr: 'Либан',
    embassy: 'Ambasada Srbije u Libanu',
    embassyCyr: 'Амбасада Србије у Либану',
    email: 'embassy@serbia-beirut.rs',
  }, {
    label: 'Liberija (pokriva UN - Njujork)',
    labelCyr: 'Либерија (покрива Уједињених нација - Нев Иорк)',
    embassy: 'UN - Njujork',
    embassyCyr: 'УН-а - Њујорк',
    email: 'info@serbiamissionun.org',
  }, {
    label: 'Libija',
    labelCyr: 'Либија',
    embassy: 'Ambasada Srbije u Libiji',
    embassyCyr: 'Амбасада Србије у Либији',
    email: 'serbianembassy_tripoli@yahoo.com',
  }, {
    label: 'Lihtenštajn (pokriva Ambasada Srbije u Švajcarskoj, Bern)',
    labelCyr: 'Лихтенштајн (поклопци Амбасада Србије у Швајцарској, Берн)',
    embassy: 'Ambasada Srbije u Švajcarskoj, Bern',
    embassyCyr: 'Амбасада Србије у Швајцарској, Берн',
    email: 'info@ambasadasrbije.ch',
  }, {
    label: 'Litvanija (pokriva Ambasada Srbije u Poljskoj)',
    labelCyr: 'Литванија (покрива Амбасада Србије у Пољској)',
    embassy: 'Ambasada Srbije u Poljskoj',
    embassyCyr: 'Амбасада Србије у Пољској',
    email: 'embassy.warsaw@mfa.rs',
  }, {
    label: 'Luksemburg (pokriva Ambasada Srbije u Belgiji)',
    labelCyr: 'Луксембург (покрива Амбасада Србије у Белгији)',
    embassy: 'Ambasada Srbije u Belgiji',
    embassyCyr: 'Амбасада Србије у Белгији',
    email: 'embassy.brussels@mfa.rs',
  }, {
    label: 'Madagaskar (pokriva UN - Njujork)',
    labelCyr: 'Мадагаскар (покрива Уједињене нације - Њујорк)',
    embassy: 'UN - Njujork',
    embassyCyr: 'УН-а - Њујорк',
    email: 'info@serbiamissionun.org',
  }, {
    label: 'Mađarska',
    labelCyr: 'Мађарска',
    embassy: 'Ambasada Srbije u Mađarskoj',
    embassyCyr: 'Амбасада Србије у Мађарској',
    email: 'budapest-consulat@serbiaemb.t-online.hu',
  }, {
    label: 'Malavi (pokriva Ambasada Srbije u Južnoafričkoj Republici)',
    labelCyr: 'Малави (покрива Амбасада Србије у Републици Јужној Африци)',
    embassy: 'Ambasada Srbije u Južnoafričkoj Republici',
    embassyCyr: 'Амбасада Србије у Јужној Африци',
    email: 'info@srbembassy.org.za',
  }, {
    label: 'Maldivi (pokriva Ambasada Srbije u Indiji)',
    labelCyr: 'Малдивес (поклопци Амбасада Србије у Индији)',
    embassy: 'Ambasada Srbije u Indiji',
    embassyCyr: 'Амбасада Србије у Индији',
    email: 'embassyofserbiadelhi@hotmail.com',
  }, {
    label: 'Malezija (pokriva Ambasada Srbije u Indoneziji)',
    labelCyr: 'Малезија (покрива Амбасада Србије у Индонезији)',
    embassy: 'Ambasada Srbije u Indoneziji',
    embassyCyr: 'Амбасада Србије у Индонезији',
    email: 'embjakarta@serbian-embassy.org',
  }, {
    label: 'Mali (pokriva Ambasada Srbije u Alžiru)',
    labelCyr: 'Мали (покрива Амбасада Србије у Алжиру)',
    embassy: 'Ambasada Srbije u Alžiru',
    embassyCyr: 'Амбасада Србије у Алжиру',
    email: 'ambasada@ambserbie-alger.com',
  }, {
    label: 'Malta (pokriva Ambasada Srbije u Italiji, Rim',
    labelCyr: 'Малта (покрива Амбасада Србије у Италији, Рим',
    embassy: 'Ambasada Srbije u Italiji, Rim',
    embassyCyr: 'Амбасада Србије у Италији, Рим',
    email: 'ljubomir.merdovic@mfa.rs',
  }, {
    label: 'Maroko',
    labelCyr: 'Мароко',
    embassy: 'Ambasada Srbije u Maroku',
    embassyCyr: 'Амбасада Србије у Мароку',
    email: 'ambrsrabat@gmail.com',
  }, {
    label: 'Mauricijus (pokriva Ambasada Srbije u Južnoafričkoj Republici)',
    labelCyr: 'Маурицијус (покрива Амбасада Србије у Јужноафричкој Републици)',
    embassy: 'Ambasada Srbije u Južnoafričkoj Republici',
    embassyCyr: 'Амбасада Србије у Јужној Африци',
    email: 'info@srbembassy.org.za',
  }, {
    label: 'Mauritanija (pokriva Ambasada Srbije u Maroku)',
    labelCyr: 'Мауританија (покрива Амбасада Србије у Мароку)',
    embassy: 'Ambasada Srbije u Maroku',
    embassyCyr: 'Амбасада Србије у Мароку',
    email: 'ambrsrabat@gmail.com',
  }, {
    label: 'Meksiko',
    labelCyr: 'Мексико',
    embassy: 'Ambasada Srbije u Meksiku',
    embassyCyr: 'Амбасада Србије у Мексику',
    email: 'embajadaserbia@alestra.net.mx',
  }, {
    label: 'Mjanmar',
    labelCyr: 'Мијанмар',
    embassy: 'Ambasada Srbije u Mjanmaru',
    embassyCyr: 'Амбасада Србије у Мјанмару',
    email: 'serbemb@yangon.net.mm',
  }, {
    label: 'Moldavija (pokriva Ambasada Srbije u Rumuniji)',
    labelCyr: 'Молдавија (покрива Амбасада Србије у Румунији)',
    embassy: 'Ambasada Srbije u Rumuniji, Bukurešt',
    embassyCyr: 'Амбасада Србије у Румунији, Букурешт',
    email: 'info@ambserbia.ro',
  }, {
    label: 'Monako (pokriva Ambasada Srbije u Francuskoj, Pariz)',
    labelCyr: 'Монако (покрива Амбасада Србије у Француској, Париз)',
    embassy: 'Ambasada Srbije u Francuskoj, Pariz',
    embassyCyr: 'Амбасада Србије у Француској, Париз',
    email: 'konzularno.pariz@mfa.rs',
  }, {
    label: 'Mongolija (pokriva Ambasada Srbije u Kini, Narodna Republika, Peking)',
    labelCyr: 'Монголија (покрива Амбасада Србије у Кини, Народна Република, Пекинг)',
    embassy: 'Ambasada Srbije u Kini, Narodna Republika, Peking',
    embassyCyr: 'Амбасада Србије у Кини, Народна Република, Пекинг',
    email: 'embserbia@embserbia.cn',
  }, {
    label: 'Mozambik (pokriva Ambasada Srbije u Južnoafričkoj Republici)',
    labelCyr: 'Мозамбик (покрива Амбасада Србије у Републици Јужној Африци)',
    embassy: 'Ambasada Srbije u Južnoafričkoj Republici',
    embassyCyr: 'Амбасада Србије у Јужној Африци',
    email: 'info@srbembassy.org.za',
  }, {
    label: 'Namibija (pokriva Ambasada Srbije u Južnoafričkoj Republici)',
    labelCyr: 'Намибија (покрива Амбасада Србије у Републици Јужној Африци)',
    embassy: 'Ambasada Srbije u Južnoafričkoj Republici',
    embassyCyr: 'Амбасада Србије у Јужној Африци',
    email: 'info@srbembassy.org.za',
  }, {
    label: 'Nemačka, Diseldorf (konzulat)',
    labelCyr: 'Немачка, Диселдорф (конзулат)',
    embassy: 'Konzulat Srbije u Nemačkoj, Diseldorf',
    embassyCyr: 'Конзулат Србије у Немачкој, Диселдорф',
    email: 'info@gksrbijedis.de',
  }, {
    label: 'Nemačka, Frankfurt (konzulat)',
    labelCyr: 'Немачка, Франкфурт (конзулат)',
    embassy: 'Konzulat Srbije u Nemačkoj, Frankfurt',
    embassyCyr: 'Конзулат Србије у Немачкој, Франкфурт',
    email: 'info@gksrbfra.de',
  }, {
    label: 'Nemačka, Hamburg (konzulat)',
    labelCyr: 'Немачка, Хамбург (конзулат)',
    embassy: 'Konzulat Srbije u Nemačkoj, Hamburg',
    embassyCyr: 'Конзулат Србије у Немачкој, Хамбург',
    email: 'gk_hamburg@web.de',
  }, {
    label: 'Nemačka, Minhen (konzulat)',
    labelCyr: 'Немачка, Минхен (конзулат)',
    embassy: 'Konzulat Srbije u Nemačkoj, Minhen',
    embassyCyr: 'Конзулат Србије у Немачкој, Минхену',
    email: 'gk.muenchen@mfa.rs',
  }, {
    label: 'Nemačka, Štutgart (konzulat)',
    labelCyr: 'Немачка, Штутгарт (конзулат)',
    embassy: 'Konzulat Srbije u Nemačkoj, Štutgart',
    embassyCyr: 'Конзулат Србије у Немачкој, Стуттгарт',
    email: 'gk-stutgart@t-online.de',
  }, {
    label: 'Nepal (pokriva Ambasada Srbije u Indiji)',
    labelCyr: 'Непал (покрива Амбасада Србије у Индији)',
    embassy: 'Ambasada Srbije u Indiji',
    embassyCyr: 'Амбасада Србије у Индији',
    email: 'embassyofserbiadelhi@hotmail.com',
  }, {
    label: 'Niger (pokriva UN - Njujork)',
    labelCyr: 'Нигер (покрива Уједињених нација - Нев Иорк)',
    embassy: 'UN - Njujork',
    embassyCyr: 'УН-а - Њујорк',
    email: 'info@serbiamissionun.org',
  }, {
    label: 'Nigerija',
    labelCyr: 'Нигерија',
    embassy: 'Ambasada Srbije u Nigeriji',
    embassyCyr: 'Амбасада Србије у Нигерији',
    email: 'serbconsabuja@gmail.com',
  }, {
    label: 'Nikaragva (pokriva Ambasada Srbije u Meksiku)',
    labelCyr: 'Никарагва (покрива Амбасада Србије у Мексику)',
    embassy: 'Ambasada Srbije u Meksiku',
    embassyCyr: 'Амбасада Србије у Мексику',
    email: 'embajadaserbia@alestra.net.mx',
  }, {
    label: 'Norveška',
    labelCyr: 'Норвешка',
    embassy: 'Ambasada Srbije u Norveškoj',
    embassyCyr: 'Амбасада Србије у Норвешкој',
    email: 'ambasada@serbianembassy.no',
  }, {
    label: 'Novi Zeland (pokriva Ambasada Srbije u Australiji, Kanbera)',
    labelCyr: 'Нови Зеланд (покрива Амбасада Србије у Аустралији, Канбера)',
    embassy: 'Ambasada Srbije u Australiji, Kanbera',
    embassyCyr: 'Амбасада Србије у Аустралији, Канбера',
    email: 'embassy.canberra@serbia.org.au',
  }, {
    label: 'Obala Slonovače (pokriva UN - Njujork)',
    labelCyr: 'Обала Слоноваче (покрива Уједињене нације - Њујорк)',
    embassy: 'UN - Njujork',
    embassyCyr: 'УН-а - Њујорк',
    email: 'info@serbiamissionun.org',
  }, {
    label: 'Oman (pokriva Ambasada Srbije u Egipatu)',
    labelCyr: 'Оман (покрива Амбасада Србије у Египату)',
    embassy: 'Ambasada Srbije u Egipatu',
    embassyCyr: 'Амбасада Србије у Египату',
    email: 'konzul@serbiaeg.com',
  }, {
    label: 'Pakistan (pokriva Ambasada Srbije u Iranu)',
    labelCyr: 'Пакистан (покрива Амбасада Србије у Ирану)',
    embassy: 'Ambasada Srbije u Iranu',
    embassyCyr: 'Амбасада Србије у Ирану',
    email: 'serbembteh@neda.net',
  }, {
    label: 'Palestina (pokriva Ambasada Srbije u Egipatu)',
    labelCyr: 'Палестина (покрива Амбасада Србије у Египату)',
    embassy: 'Ambasada Srbije u Egipatu',
    embassyCyr: 'Амбасада Србије у Египату',
    email: 'konzul@serbiaeg.com',
  }, {
    label: 'Panama (pokriva Ambasada Srbije u Meksiku)',
    labelCyr: 'Панама (покрива амбасада Србије у Мексику)',
    embassy: 'Ambasada Srbije u Meksiku',
    embassyCyr: 'Амбасада Србије у Мексику',
    email: 'embajadaserbia@alestra.net.mx',
  }, {
    label: 'Papua Nova Gvineja (pokriva Ambasada Srbije u Australiji, Kanbera)',
    labelCyr: 'Папуа Нова Гвинеја (покрива Амбасада Србије у Аустралији, Канбера)',
    embassy: 'Ambasada Srbije u Australiji, Kanbera',
    embassyCyr: 'Амбасада Србије у Аустралији, Канбера',
    email: 'embassy.canberra@serbia.org.au',
  }, {
    label: 'Paragvaj (pokriva Ambasada Srbije u Argentini)',
    labelCyr: 'Парагвај (покрива Амбасада Србије у Аргентини)',
    embassy: 'Ambasada Srbije u Argentini',
    embassyCyr: 'Амбасада Србије у Аргентини',
    email: 'consulado@serbembaires.com.ar',
  }, {
    label: 'Peru (pokriva Ambasada Srbije u Argentini)',
    labelCyr: 'Перу (покрива Амбасада Србије у Аргентини)',
    embassy: 'Ambasada Srbije u Argentini',
    embassyCyr: 'Амбасада Србије у Аргентини',
    email: 'consulado@serbembaires.com.ar',
  }, {
    label: 'Poljska',
    labelCyr: 'Пољска',
    embassy: 'Ambasada Srbije u Poljskoj',
    embassyCyr: 'Амбасада Србије у Пољској',
    email: 'embassy.warsaw@mfa.rs',
  }, {
    label: 'Portugal',
    labelCyr: 'Португалија',
    embassy: 'Ambasada Srbije u Portugalu',
    embassyCyr: 'Амбасада Србије у Португалу',
    email: 'serviaemba@netcabo.pt',
  }, {
    label: 'Ruanda (pokriva Ambasada Srbije u Keniji)',
    labelCyr: 'Руанда (покрива Амбасада Србије у Кенији)',
    embassy: 'Ambasada Srbije u Keniji',
    embassyCyr: 'Амбасада Србије у Кенији',
    email: 'nairobi@embassyofserbia.or.ke',
  }, {
    label: 'Rumunija',
    labelCyr: 'Румунија',
    embassy: 'Ambasada Srbije u Rumuniji, Bukurešt',
    embassyCyr: 'Амбасада Србије у Румунији, Букурешт',
    email: 'info@ambserbia.ro',
  }, {
    label: 'Rumunija, Temišvar (konzulat)',
    labelCyr: 'Румунија, Тимисоара (конзулат)',
    embassy: 'Konzulat Srbije u Rumuniji, Temišvar',
    embassyCyr: 'Конзулат Србије у Румунији, Темишвар',
    email: 'gktemisvar@gmail.com',
  }, {
    label: 'Rusija',
    labelCyr: 'Русија',
    embassy: 'Ambasada Srbije u Rusiji',
    embassyCyr: 'Амбасада Србије у Русији',
    email: 'konzularno.moskva@mfa.rs',
  }, {
    label: 'SAD, Čikago (konzulat)',
    labelCyr: 'УСА, Цхицаго (конзулат)',
    embassy: 'Konzulat Srbije u Sjedinjenim Američkim Državama, Čikago',
    embassyCyr: 'Конзулат Србије у Сједињеним Америчким Државама, Цхицаго',
    email: 'info@scgchicago.org',
  }, {
    label: 'SAD, Njujork (konzulat)',
    labelCyr: 'САД, Њујорк (конзулат)',
    embassy: 'Konzulat Srbije u Sjedinjenim Američkim Državama, Njujork',
    embassyCyr: 'Конзулат Србије у Сједињеним Америчким Државама, Нев Иорк',
    email: 'izbori.njujork2020@mfa.rs',
  }, {
    label: 'SAD, Vašington',
    labelCyr: 'САД, Вашингтон',
    embassy: 'Ambasada Srbije u Sjedinjenim Američkim Državama, Vašington',
    embassyCyr: 'Амбасада Србије у Сједињеним Америчким Државама, Васхингтон',
    email: 'consular@serbiaembusa.org',
  }, {
    label: 'Salvadaor (pokriva Ambasada Srbije u Meksiku)',
    labelCyr: 'Салвадаор (покрива Амбасада Србије у Мексику)',
    embassy: 'Ambasada Srbije u Meksiku',
    embassyCyr: 'Амбасада Србије у Мексику',
    email: 'embajadaserbia@alestra.net.mx',
  }, {
    label: 'Samoa (pokriva Ambasada Srbije u Australiji, Kanbera)',
    labelCyr: 'Самоа (покрива Амбасада Србије у Аустралији, Канбера)',
    embassy: 'Ambasada Srbije u Australiji, Kanbera',
    embassyCyr: 'Амбасада Србије у Аустралији, Канбера',
    email: 'embassy.canberra@serbia.org.au',
  }, {
    label: 'San Marino (pokriva Ambasada Srbije u Italiji, Rim)',
    labelCyr: 'Сан Марино (покрива Амбасада Србије у Италији, Рим)',
    embassy: 'Ambasada Srbije u Italiji, Rim',
    embassyCyr: 'Амбасада Србије у Италији, Рим',
    email: 'ljubomir.merdovic@mfa.rs',
  }, {
    label: 'Sao Tome i Principe (pokriva UN - Njujork)',
    labelCyr: 'Сао Томе и Принципе (покрива Уједињене нације - Њујорк)',
    embassy: 'UN - Njujork',
    embassyCyr: 'УН-а - Њујорк',
    email: 'info@serbiamissionun.org',
  }, {
    label: 'Saudijska Arabija',
    labelCyr: 'Саудијска Арабија',
    embassy: 'Ambasada Srbije u Saudijskoj Arabiji',
    embassyCyr: 'Амбасада Србије у Саудијској Арабији',
    email: 'embsrb.riyadh@yahoo.com',
  }, {
    label: 'Sejšeli (pokriva Ambasada Srbije u Etiopiji)',
    labelCyr: 'Сејшели (покрива Амбасада Србије у Етиопији)',
    embassy: 'Ambasada Srbije u Etiopiji',
    embassyCyr: 'Амбасада Србије у Етиопији',
    email: 'serbambadis@yahoo.com',
  }, {
    label: 'Senegal (pokriva Ambasada Srbije u Maroku)',
    labelCyr: 'Сенегал (покрива Амбасада Србије у Мароку)',
    embassy: 'Ambasada Srbije u Maroku',
    embassyCyr: 'Амбасада Србије у Мароку',
    email: 'ambrsrabat@gmail.com',
  }, {
    label: 'Sent Kits i Nevis (pokriva Ambasada Srbije u SAD, Vašington)',
    labelCyr: 'Сент Китс и Невис (покрива Амбасада Србије у САД, Вашингтон)',
    embassy: 'Ambasada Srbije u Sjedinjenim Američkim Državama, Vašington',
    embassyCyr: 'Амбасада Србије у Сједињеним Америчким Државама, Васхингтон',
    email: 'consular@serbiaembusa.org',
  }, {
    label: 'Sent Vinsent i Grenadini (pokriva Ambasada Srbije u SAD, Vašington)',
    labelCyr: 'Сент Винсент и Гренадини (покрива Амбасада Србије у САД, Вашингтон)',
    embassy: 'Ambasada Srbije u Sjedinjenim Američkim Državama, Vašington',
    embassyCyr: 'Амбасада Србије у Сједињеним Америчким Државама, Васхингтон',
    email: 'consular@serbiaembusa.org',
  }, {
    label: 'Severna Makedonija',
    labelCyr: 'Северна Македонија',
    embassy: 'Ambasada Srbije u Severnoj Makedoniji',
    embassyCyr: 'Амбасада Србије у Северна Македонија',
    email: 'srbamb@unet.com.mk',
  }, {
    label: 'Sijera Leone (pokriva UN - Njujork)',
    labelCyr: 'Сијера Леоне (покрива УН - Њујорк)',
    embassy: 'UN - Njujork',
    embassyCyr: 'УН-а - Њујорк',
    email: 'info@serbiamissionun.org',
  }, {
    label: 'Singapur (pokriva Ambasada Srbije u Indoneziji)',
    labelCyr: 'Сингапур (покрива Амбасада Србије у Индонезији)',
    embassy: 'Ambasada Srbije u Indoneziji',
    embassyCyr: 'Амбасада Србије у Индонезији',
    email: 'embjakarta@serbian-embassy.org',
  }, {
    label: 'Sirija',
    labelCyr: 'Сирија',
    embassy: 'Ambasada Srbije u Siriji',
    embassyCyr: 'Амбасада Србије у Сирији',
    email: 'ambasada@srbija-damask.org',
  }, {
    label: 'Slovačka',
    labelCyr: 'Словачка',
    embassy: 'Ambasada Srbije u Slovačkoj',
    embassyCyr: 'Амбасада Србије у Словачкој',
    email: 'embassy.bratislava@mfa.rs',
  }, {
    label: 'Slovenija',
    labelCyr: 'Словенија',
    embassy: 'Ambasada Srbije u Sloveniji',
    embassyCyr: 'Амбасада Србије у Словенији',
    email: 'embassy.ljubljana@mfa.rs',
  }, {
    label: 'Somalija (pokriva Ambasada Srbije u Keniji)',
    labelCyr: 'Сомалија (покрива Амбасада Србије у Кенији)',
    embassy: 'Ambasada Srbije u Keniji',
    embassyCyr: 'Амбасада Србије у Кенији',
    email: 'nairobi@embassyofserbia.or.ke',
  }, {
    label: 'Španija',
    labelCyr: 'Шпанија',
    embassy: 'Ambasada Srbije u Španiji',
    embassyCyr: 'Амбасада Србије у Шпанији',
    email: 'konz.madrid@mfa.rs',
  }, {
    label: 'Šri Lanka (pokriva Ambasada Srbije u Indiji)',
    labelCyr: 'Шри Ланка (покрива Амбасада Србије у Индији)',
    embassy: 'Ambasada Srbije u Indiji',
    embassyCyr: 'Амбасада Србије у Индији',
    email: 'embassyofserbiadelhi@hotmail.com',
  }, {
    label: 'Sudan (pokriva Ambasada Srbije u Egipatu)',
    labelCyr: 'Судан (покрива Амбасада Србије у Египату)',
    embassy: 'Ambasada Srbije u Egipatu',
    embassyCyr: 'Амбасада Србије у Египату',
    email: 'konzul@serbiaeg.com',
  }, {
    label: 'Surinam (pokriva Ambasada Srbije u SAD, Vašington)',
    labelCyr: 'Суринам (покрива Амбасада Србије у САД, Вашингтон)',
    embassy: 'Ambasada Srbije u Sjedinjenim Američkim Državama, Vašington',
    embassyCyr: 'Амбасада Србије у Сједињеним Америчким Државама, Васхингтон',
    email: 'consular@serbiaembusa.org',
  }, {
    label: 'Švajcarska, Cirih (konzulat)',
    labelCyr: 'Свитзерланд, Зурицх (конзулат)',
    embassy: 'Konzulat Srbije u Švajcarskoj, Cirih',
    embassyCyr: 'Конзулат Србије у Швајцарској, Цириху',
    email: 'info@konzulat.ch',
  }, {
    label: 'Svazilend (pokriva Ambasada Srbije u Južnoafričkoj Republici)',
    labelCyr: 'Свазиленд (покрива Амбасада Србије у Републици Јужној Африци)',
    embassy: 'Ambasada Srbije u Južnoafričkoj Republici',
    embassyCyr: 'Амбасада Србије у Јужној Африци',
    email: 'info@srbembassy.org.za',
  }, {
    label: 'Švedska',
    labelCyr: 'Шведска',
    embassy: 'Ambasada Srbije u Švedskoj',
    embassyCyr: 'Амбасада Србије у Шведској',
    email: 'serbiaemb@telia.com',
  }, {
    label: 'Sveta Lucija (pokriva Ambasada Srbije u SAD, Vašington)',
    labelCyr: 'Света Луција (поклопци Амбасада Србије у Сједињеним Америчким Државама, Вашингтон)',
    embassy: 'Ambasada Srbije u Sjedinjenim Američkim Državama, Vašington',
    embassyCyr: 'Амбасада Србије у Сједињеним Америчким Државама, Васхингтон',
    email: 'consular@serbiaembusa.org',
  }, {
    label: 'Tadžikistan (pokriva Ambasada Srbije u Etiopiji)',
    labelCyr: 'Таџикистан (покрива Амбасада Србије у Етиопији)',
    embassy: 'Ambasada Srbije u Etiopiji',
    embassyCyr: 'Амбасада Србије у Етиопији',
    email: 'serbambadis@yahoo.com',
  }, {
    label: 'Tajland (pokriva Ambasada Srbije u Indoneziji)',
    labelCyr: 'Тајланд (покрива Амбасада Србије у Индонезији)',
    embassy: 'Ambasada Srbije u Indoneziji',
    embassyCyr: 'Амбасада Србије у Индонезији',
    email: 'embjakarta@serbian-embassy.org',
  }, {
    label: 'Tanzanija (pokriva Ambasada Srbije u Rusiji)',
    labelCyr: 'Танзанија (поклопци Амбасада Србије у Русији)',
    embassy: 'Ambasada Srbije u Rusiji',
    embassyCyr: 'Амбасада Србије у Русији',
    email: 'konzularno.moskva@mfa.rs',
  }, {
    label: 'Togo (pokriva UN - Njujork)',
    labelCyr: 'Того (покрива Уједињених нација - Нев Иорк)',
    embassy: 'UN - Njujork',
    embassyCyr: 'УН-а - Њујорк',
    email: 'info@serbiamissionun.org',
  }, {
    label: 'Tonga (pokriva Ambasada Srbije u Australiji, Kanbera)',
    labelCyr: 'Тонга (покрива Амбасада Србије у Аустралији, Канбера)',
    embassy: 'Ambasada Srbije u Australiji, Kanbera',
    embassyCyr: 'Амбасада Србије у Аустралији, Канбера',
    email: 'embassy.canberra@serbia.org.au',
  }, {
    label: 'Trinidad i Tobago (pokriva Ambasada Srbije u SAD, Vašington)',
    labelCyr: 'Тринидад и Тобаго (поклопци Амбасада Србије у Сједињеним Америчким Државама, Вашингтон)',
    embassy: 'Ambasada Srbije u Sjedinjenim Američkim Državama, Vašington',
    embassyCyr: 'Амбасада Србије у Сједињеним Америчким Државама, Васхингтон',
    email: 'consular@serbiaembusa.org',
  }, {
    label: 'Tunis',
    labelCyr: 'Тунис',
    embassy: 'Ambasada Srbije u Tunisu',
    embassyCyr: 'Амбасада Србије у Тунису',
    email: 'amb.serbia@gnet.tn',
  }, {
    label: 'Turkmenistan (pokriva Ambasada Srbije u Rusiji)',
    labelCyr: 'Туркменистан (покрива Амбасада Србије у Русији)',
    embassy: 'Ambasada Srbije u Rusiji',
    embassyCyr: 'Амбасада Србије у Русији',
    email: 'konzularno.moskva@mfa.rs',
  }, {
    label: 'Turksa, Ankara',
    labelCyr: 'Турци, Анкари',
    embassy: 'Ambasada Srbije u Turskoj, Ankara',
    embassyCyr: 'Амбасада Србије у Турској, Анкара',
    email: 'embserank@gmail.com',
  }, {
    label: 'Turska, Istanbul (konzulat)',
    labelCyr: 'Турска, Истанбул (конзулат)',
    embassy: 'Konzulat Srbije u Turskoj, Istanbul',
    embassyCyr: 'Конзулат Србије у Турској, Истанбул',
    email: 'konzulat.istanbul@mfa.rs',
  }, {
    label: 'Uganda (pokriva Ambasada Srbije u Keniji)',
    labelCyr: 'Уганда (поклопци Амбасада Србије у Кенији)',
    embassy: 'Ambasada Srbije u Keniji',
    embassyCyr: 'Амбасада Србије у Кенији',
    email: 'nairobi@embassyofserbia.or.ke',
  }, {
    label: 'Ujedinjeni Arapski Emirati',
    labelCyr: 'Уједињени Арапски Емирати',
    embassy: 'Ambasada Srbije u Ujedinjenim Arapskim Emiratima',
    embassyCyr: 'Амбасада Србије у Уједињеним Арапским Емиратима',
    email: 'embassy.abudhabi@mfa.rs',
  }, {
    label: 'Ukrajina',
    labelCyr: 'Украјина',
    embassy: 'Ambasada Srbije u Ukrajini',
    embassyCyr: 'Амбасада Србије у Украјини',
    email: 'konzrs@ukr.net',
  }, {
    label: 'Urugvaj (pokriva Ambasada Srbije u Argentini)',
    labelCyr: 'Уругвај (покрива Амбасада Србије у Аргентини)',
    embassy: 'Ambasada Srbije u Argentini',
    embassyCyr: 'Амбасада Србије у Аргентини',
    email: 'consulado@serbembaires.com.ar',
  }, {
    label: 'Uzbekistan (pokriva Ambasada Srbije u Rusiji)',
    labelCyr: 'Узбекистан (покрива Амбасада Србије у Русији)',
    embassy: 'Ambasada Srbije u Rusiji',
    embassyCyr: 'Амбасада Србије у Русији',
    email: 'konzularno.moskva@mfa.rs',
  }, {
    label: 'Vanuatu (pokriva Ambasada Srbije u Australiji, Kanbera',
    labelCyr: 'Вануату (покрива Амбасада Србије у Аустралији, Канбера',
    embassy: 'Ambasada Srbije u Australiji, Kanbera',
    embassyCyr: 'Амбасада Србије у Аустралији, Канбера',
    email: 'embassy.canberra@serbia.org.au',
  }, {
    label: 'Vatikan',
    labelCyr: 'Ватикан',
    embassy: 'Ambasada Srbije u Vatikanu',
    embassyCyr: 'Амбасада Србије у Ватикану',
    email: 'amb.serbia.vatican@ambroma.com',
  }, {
    label: 'Velika Britanija',
    labelCyr: 'Велика Британија',
    embassy: 'Ambasada Srbije u Velikoj Britaniji',
    embassyCyr: 'Амбасада Србије у Великој Британији',
    email: 'izbori2020@serbianembassy.org.uk',
  }, {
    label: 'Venecuela (pokriva Ambasada Srbije na Kubi)',
    labelCyr: 'Венецуела (покрива Амбасада Србије на Куби)',
    embassy: 'Ambasada Srbije na Kubi',
    embassyCyr: 'Амбасада Србије на Куби',
    email: 'konzsrbhav@gmail.com',
  }, {
    label: 'Vijetnam (pokriva Ambasada Srbije u Indoneziji)',
    labelCyr: 'Вијетнам (покрива Амбасада Србије у Индонезији)',
    embassy: 'Ambasada Srbije u Indoneziji',
    embassyCyr: 'Амбасада Србије у Индонезији',
    email: 'embjakarta@serbian-embassy.org',
  }, {
    label: 'Zambija',
    labelCyr: 'Замбија',
    embassy: 'Ambasada Srbije u Zambiji',
    embassyCyr: 'Амбасада Србије у Замбији',
    email: 'serbia.lusaka@iconnect.zm',
  }, {
    label: 'Zambija (pokriva Ambasada Srbije u Južnoafričkoj Republici)',
    labelCyr: 'Замбија (покрива Амбасада Србије у Републици Јужној Африци)',
    embassy: 'Ambasada Srbije u Južnoafričkoj Republici',
    embassyCyr: 'Амбасада Србије у Јужној Африци',
    email: 'info@srbembassy.org.za',
  }, {
    label: 'Zelenortska ostrva (pokriva Ambasada Srbije u Južnoafričkoj Republici)',
    labelCyr: 'Капе Верде (покрива Амбасада Србије у Републици Јужној Африци)',
    embassy: 'Ambasada Srbije u Južnoafričkoj Republici',
    embassyCyr: 'Амбасада Србије у Јужној Африци',
    email: 'info@srbembassy.org.za',
  }, {
    label: 'Zimbabve (pokriva Ambasada Srbije u Portugalu)',
    labelCyr: 'Зимбабве (покрива Амбасада Србије у Португалу)',
    embassy: 'Ambasada Srbije u Portugalu',
    embassyCyr: 'Амбасада Србије у Португалу',
    email: 'serviaemba@netcabo.pt',
  }
];
